# @package config

lr: 2e-5
seed: 123
gradient_accumulation_steps: 1
weight_decay: 0.01
pretrained_no_yamlconfig: false
nb_iterations: 150000
train_batch_size: 32  # number of gpus needs to divide this
eval_batch_size: 128
index_retrieve_batch_size: 500
record_frequency: 10000
train_monitoring_freq: 5
warmup_steps: 6000
max_length: 256
fp16: false
matching_type: cross_encoder