
init_checkpoint: output/model/runs/mmp_pep10_point/model_20000
q_term_path: data/msmarco/dev_sample1000/query_terms.txt
d_term_path: output/mmp/d_terms_top100K.txt
run_name: pep_tt
score_save_dir: output/mmp/dev1000_d_terms_pep
bm25conf_path: confs/bm25_resource/bt2.yaml


eval_steps: 1000
batch_size: 64
steps_per_execution: 1
train_data_dir: data/msmarco/triples.train.train
eval_data_dir: data/msmarco/triples.train.eval
model_save_dir: output/model/runs/pep_tt_1