# Training with more alignment candidates


init_checkpoint: output/model/runs/mmp_pep10_point/model_20000
run_name: pep_tt10

bm25conf_path: confs/bm25_resource/bt2_49.yaml
align_info_conf: confs/experiment_confs/triples_train_alignment_cands.yaml
# This has 1,000,000 q/d+/d- triplets
#

batch_size: 256
train_step: 10000
save_every_n_step: 1000
eval_every_n_step: 1000000
steps_per_execution: 1
dataset_path: data/msmarco/triples.train.full
model_save_path: output/model/runs/pep_tt10
