v2_ckpt_variables_raw = """_CHECKPOINTABLE_OBJECT_GRAPH
model/layer_with_weights-0/embeddings/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-1/embeddings/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-10/_attention_layer/_key_dense/bias/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-10/_attention_layer/_key_dense/kernel/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-10/_attention_layer/_query_dense/bias/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-10/_attention_layer/_query_dense/kernel/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-10/_attention_layer/_value_dense/bias/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-10/_attention_layer/_value_dense/kernel/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-10/_attention_layer_norm/beta/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-10/_attention_layer_norm/gamma/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-10/_attention_output_dense/bias/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-10/_attention_output_dense/kernel/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-10/_intermediate_dense/bias/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-10/_intermediate_dense/kernel/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-10/_output_dense/bias/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-10/_output_dense/kernel/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-10/_output_layer_norm/beta/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-10/_output_layer_norm/gamma/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-11/_attention_layer/_key_dense/bias/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-11/_attention_layer/_key_dense/kernel/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-11/_attention_layer/_query_dense/bias/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-11/_attention_layer/_query_dense/kernel/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-11/_attention_layer/_value_dense/bias/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-11/_attention_layer/_value_dense/kernel/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-11/_attention_layer_norm/beta/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-11/_attention_layer_norm/gamma/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-11/_attention_output_dense/bias/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-11/_attention_output_dense/kernel/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-11/_intermediate_dense/bias/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-11/_intermediate_dense/kernel/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-11/_output_dense/bias/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-11/_output_dense/kernel/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-11/_output_layer_norm/beta/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-11/_output_layer_norm/gamma/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-12/_attention_layer/_key_dense/bias/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-12/_attention_layer/_key_dense/kernel/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-12/_attention_layer/_query_dense/bias/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-12/_attention_layer/_query_dense/kernel/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-12/_attention_layer/_value_dense/bias/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-12/_attention_layer/_value_dense/kernel/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-12/_attention_layer_norm/beta/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-12/_attention_layer_norm/gamma/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-12/_attention_output_dense/bias/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-12/_attention_output_dense/kernel/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-12/_intermediate_dense/bias/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-12/_intermediate_dense/kernel/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-12/_output_dense/bias/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-12/_output_dense/kernel/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-12/_output_layer_norm/beta/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-12/_output_layer_norm/gamma/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-13/_attention_layer/_key_dense/bias/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-13/_attention_layer/_key_dense/kernel/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-13/_attention_layer/_query_dense/bias/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-13/_attention_layer/_query_dense/kernel/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-13/_attention_layer/_value_dense/bias/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-13/_attention_layer/_value_dense/kernel/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-13/_attention_layer_norm/beta/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-13/_attention_layer_norm/gamma/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-13/_attention_output_dense/bias/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-13/_attention_output_dense/kernel/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-13/_intermediate_dense/bias/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-13/_intermediate_dense/kernel/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-13/_output_dense/bias/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-13/_output_dense/kernel/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-13/_output_layer_norm/beta/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-13/_output_layer_norm/gamma/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-14/_attention_layer/_key_dense/bias/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-14/_attention_layer/_key_dense/kernel/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-14/_attention_layer/_query_dense/bias/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-14/_attention_layer/_query_dense/kernel/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-14/_attention_layer/_value_dense/bias/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-14/_attention_layer/_value_dense/kernel/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-14/_attention_layer_norm/beta/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-14/_attention_layer_norm/gamma/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-14/_attention_output_dense/bias/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-14/_attention_output_dense/kernel/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-14/_intermediate_dense/bias/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-14/_intermediate_dense/kernel/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-14/_output_dense/bias/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-14/_output_dense/kernel/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-14/_output_layer_norm/beta/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-14/_output_layer_norm/gamma/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-15/_attention_layer/_key_dense/bias/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-15/_attention_layer/_key_dense/kernel/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-15/_attention_layer/_query_dense/bias/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-15/_attention_layer/_query_dense/kernel/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-15/_attention_layer/_value_dense/bias/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-15/_attention_layer/_value_dense/kernel/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-15/_attention_layer_norm/beta/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-15/_attention_layer_norm/gamma/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-15/_attention_output_dense/bias/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-15/_attention_output_dense/kernel/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-15/_intermediate_dense/bias/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-15/_intermediate_dense/kernel/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-15/_output_dense/bias/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-15/_output_dense/kernel/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-15/_output_layer_norm/beta/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-15/_output_layer_norm/gamma/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-16/bias/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-16/kernel/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-2/embeddings/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-3/beta/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-3/gamma/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-4/_attention_layer/_key_dense/bias/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-4/_attention_layer/_key_dense/kernel/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-4/_attention_layer/_query_dense/bias/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-4/_attention_layer/_query_dense/kernel/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-4/_attention_layer/_value_dense/bias/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-4/_attention_layer/_value_dense/kernel/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-4/_attention_layer_norm/beta/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-4/_attention_layer_norm/gamma/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-4/_attention_output_dense/bias/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-4/_attention_output_dense/kernel/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-4/_intermediate_dense/bias/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-4/_intermediate_dense/kernel/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-4/_output_dense/bias/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-4/_output_dense/kernel/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-4/_output_layer_norm/beta/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-4/_output_layer_norm/gamma/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-5/_attention_layer/_key_dense/bias/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-5/_attention_layer/_key_dense/kernel/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-5/_attention_layer/_query_dense/bias/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-5/_attention_layer/_query_dense/kernel/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-5/_attention_layer/_value_dense/bias/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-5/_attention_layer/_value_dense/kernel/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-5/_attention_layer_norm/beta/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-5/_attention_layer_norm/gamma/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-5/_attention_output_dense/bias/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-5/_attention_output_dense/kernel/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-5/_intermediate_dense/bias/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-5/_intermediate_dense/kernel/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-5/_output_dense/bias/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-5/_output_dense/kernel/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-5/_output_layer_norm/beta/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-5/_output_layer_norm/gamma/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-6/_attention_layer/_key_dense/bias/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-6/_attention_layer/_key_dense/kernel/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-6/_attention_layer/_query_dense/bias/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-6/_attention_layer/_query_dense/kernel/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-6/_attention_layer/_value_dense/bias/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-6/_attention_layer/_value_dense/kernel/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-6/_attention_layer_norm/beta/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-6/_attention_layer_norm/gamma/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-6/_attention_output_dense/bias/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-6/_attention_output_dense/kernel/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-6/_intermediate_dense/bias/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-6/_intermediate_dense/kernel/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-6/_output_dense/bias/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-6/_output_dense/kernel/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-6/_output_layer_norm/beta/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-6/_output_layer_norm/gamma/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-7/_attention_layer/_key_dense/bias/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-7/_attention_layer/_key_dense/kernel/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-7/_attention_layer/_query_dense/bias/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-7/_attention_layer/_query_dense/kernel/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-7/_attention_layer/_value_dense/bias/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-7/_attention_layer/_value_dense/kernel/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-7/_attention_layer_norm/beta/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-7/_attention_layer_norm/gamma/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-7/_attention_output_dense/bias/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-7/_attention_output_dense/kernel/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-7/_intermediate_dense/bias/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-7/_intermediate_dense/kernel/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-7/_output_dense/bias/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-7/_output_dense/kernel/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-7/_output_layer_norm/beta/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-7/_output_layer_norm/gamma/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-8/_attention_layer/_key_dense/bias/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-8/_attention_layer/_key_dense/kernel/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-8/_attention_layer/_query_dense/bias/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-8/_attention_layer/_query_dense/kernel/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-8/_attention_layer/_value_dense/bias/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-8/_attention_layer/_value_dense/kernel/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-8/_attention_layer_norm/beta/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-8/_attention_layer_norm/gamma/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-8/_attention_output_dense/bias/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-8/_attention_output_dense/kernel/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-8/_intermediate_dense/bias/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-8/_intermediate_dense/kernel/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-8/_output_dense/bias/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-8/_output_dense/kernel/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-8/_output_layer_norm/beta/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-8/_output_layer_norm/gamma/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-9/_attention_layer/_key_dense/bias/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-9/_attention_layer/_key_dense/kernel/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-9/_attention_layer/_query_dense/bias/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-9/_attention_layer/_query_dense/kernel/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-9/_attention_layer/_value_dense/bias/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-9/_attention_layer/_value_dense/kernel/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-9/_attention_layer_norm/beta/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-9/_attention_layer_norm/gamma/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-9/_attention_output_dense/bias/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-9/_attention_output_dense/kernel/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-9/_intermediate_dense/bias/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-9/_intermediate_dense/kernel/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-9/_output_dense/bias/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-9/_output_dense/kernel/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-9/_output_layer_norm/beta/.ATTRIBUTES/VARIABLE_VALUE
model/layer_with_weights-9/_output_layer_norm/gamma/.ATTRIBUTES/VARIABLE_VALUE
save_counter/.ATTRIBUTES/VARIABLE_VALUE
"""
module_variables_raw = """encoder1/word_embeddings/embeddings:0
encoder1/embeddings/layer_norm/gamma:0
encoder1/embeddings/layer_norm/beta:0
encoder1/pooler_transform/kernel:0
encoder1/pooler_transform/bias:0
encoder1/position_embedding/embeddings:0
encoder1/transformer/layer_0/self_attention/key/kernel:0
encoder1/transformer/layer_0/self_attention/key/bias:0
encoder1/transformer/layer_0/self_attention/attention_output/kernel:0
encoder1/transformer/layer_0/self_attention/attention_output/bias:0
encoder1/transformer/layer_0/self_attention/query/kernel:0
encoder1/transformer/layer_0/self_attention/query/bias:0
encoder1/transformer/layer_0/self_attention/value/kernel:0
encoder1/transformer/layer_0/self_attention/value/bias:0
encoder1/transformer/layer_0/self_attention_layer_norm/gamma:0
encoder1/transformer/layer_0/self_attention_layer_norm/beta:0
encoder1/transformer/layer_0/intermediate/kernel:0
encoder1/transformer/layer_0/intermediate/bias:0
encoder1/transformer/layer_0/output/kernel:0
encoder1/transformer/layer_0/output/bias:0
encoder1/transformer/layer_0/output_layer_norm/gamma:0
encoder1/transformer/layer_0/output_layer_norm/beta:0
encoder1/transformer/layer_1/self_attention/key/kernel:0
encoder1/transformer/layer_1/self_attention/key/bias:0
encoder1/transformer/layer_1/self_attention/attention_output/kernel:0
encoder1/transformer/layer_1/self_attention/attention_output/bias:0
encoder1/transformer/layer_1/self_attention/query/kernel:0
encoder1/transformer/layer_1/self_attention/query/bias:0
encoder1/transformer/layer_1/self_attention/value/kernel:0
encoder1/transformer/layer_1/self_attention/value/bias:0
encoder1/transformer/layer_1/self_attention_layer_norm/gamma:0
encoder1/transformer/layer_1/self_attention_layer_norm/beta:0
encoder1/transformer/layer_1/intermediate/kernel:0
encoder1/transformer/layer_1/intermediate/bias:0
encoder1/transformer/layer_1/output/kernel:0
encoder1/transformer/layer_1/output/bias:0
encoder1/transformer/layer_1/output_layer_norm/gamma:0
encoder1/transformer/layer_1/output_layer_norm/beta:0
encoder1/transformer/layer_2/self_attention/key/kernel:0
encoder1/transformer/layer_2/self_attention/key/bias:0
encoder1/transformer/layer_2/self_attention/attention_output/kernel:0
encoder1/transformer/layer_2/self_attention/attention_output/bias:0
encoder1/transformer/layer_2/self_attention/query/kernel:0
encoder1/transformer/layer_2/self_attention/query/bias:0
encoder1/transformer/layer_2/self_attention/value/kernel:0
encoder1/transformer/layer_2/self_attention/value/bias:0
encoder1/transformer/layer_2/self_attention_layer_norm/gamma:0
encoder1/transformer/layer_2/self_attention_layer_norm/beta:0
encoder1/transformer/layer_2/intermediate/kernel:0
encoder1/transformer/layer_2/intermediate/bias:0
encoder1/transformer/layer_2/output/kernel:0
encoder1/transformer/layer_2/output/bias:0
encoder1/transformer/layer_2/output_layer_norm/gamma:0
encoder1/transformer/layer_2/output_layer_norm/beta:0
encoder1/transformer/layer_3/self_attention/key/kernel:0
encoder1/transformer/layer_3/self_attention/key/bias:0
encoder1/transformer/layer_3/self_attention/attention_output/kernel:0
encoder1/transformer/layer_3/self_attention/attention_output/bias:0
encoder1/transformer/layer_3/self_attention/query/kernel:0
encoder1/transformer/layer_3/self_attention/query/bias:0
encoder1/transformer/layer_3/self_attention/value/kernel:0
encoder1/transformer/layer_3/self_attention/value/bias:0
encoder1/transformer/layer_3/self_attention_layer_norm/gamma:0
encoder1/transformer/layer_3/self_attention_layer_norm/beta:0
encoder1/transformer/layer_3/intermediate/kernel:0
encoder1/transformer/layer_3/intermediate/bias:0
encoder1/transformer/layer_3/output/kernel:0
encoder1/transformer/layer_3/output/bias:0
encoder1/transformer/layer_3/output_layer_norm/gamma:0
encoder1/transformer/layer_3/output_layer_norm/beta:0
encoder1/transformer/layer_4/self_attention/key/kernel:0
encoder1/transformer/layer_4/self_attention/key/bias:0
encoder1/transformer/layer_4/self_attention/attention_output/kernel:0
encoder1/transformer/layer_4/self_attention/attention_output/bias:0
encoder1/transformer/layer_4/self_attention/query/kernel:0
encoder1/transformer/layer_4/self_attention/query/bias:0
encoder1/transformer/layer_4/self_attention/value/kernel:0
encoder1/transformer/layer_4/self_attention/value/bias:0
encoder1/transformer/layer_4/self_attention_layer_norm/gamma:0
encoder1/transformer/layer_4/self_attention_layer_norm/beta:0
encoder1/transformer/layer_4/intermediate/kernel:0
encoder1/transformer/layer_4/intermediate/bias:0
encoder1/transformer/layer_4/output/kernel:0
encoder1/transformer/layer_4/output/bias:0
encoder1/transformer/layer_4/output_layer_norm/gamma:0
encoder1/transformer/layer_4/output_layer_norm/beta:0
encoder1/transformer/layer_5/self_attention/key/kernel:0
encoder1/transformer/layer_5/self_attention/key/bias:0
encoder1/transformer/layer_5/self_attention/attention_output/kernel:0
encoder1/transformer/layer_5/self_attention/attention_output/bias:0
encoder1/transformer/layer_5/self_attention/query/kernel:0
encoder1/transformer/layer_5/self_attention/query/bias:0
encoder1/transformer/layer_5/self_attention/value/kernel:0
encoder1/transformer/layer_5/self_attention/value/bias:0
encoder1/transformer/layer_5/self_attention_layer_norm/gamma:0
encoder1/transformer/layer_5/self_attention_layer_norm/beta:0
encoder1/transformer/layer_5/intermediate/kernel:0
encoder1/transformer/layer_5/intermediate/bias:0
encoder1/transformer/layer_5/output/kernel:0
encoder1/transformer/layer_5/output/bias:0
encoder1/transformer/layer_5/output_layer_norm/gamma:0
encoder1/transformer/layer_5/output_layer_norm/beta:0
encoder1/transformer/layer_6/self_attention/key/kernel:0
encoder1/transformer/layer_6/self_attention/key/bias:0
encoder1/transformer/layer_6/self_attention/attention_output/kernel:0
encoder1/transformer/layer_6/self_attention/attention_output/bias:0
encoder1/transformer/layer_6/self_attention/query/kernel:0
encoder1/transformer/layer_6/self_attention/query/bias:0
encoder1/transformer/layer_6/self_attention/value/kernel:0
encoder1/transformer/layer_6/self_attention/value/bias:0
encoder1/transformer/layer_6/self_attention_layer_norm/gamma:0
encoder1/transformer/layer_6/self_attention_layer_norm/beta:0
encoder1/transformer/layer_6/intermediate/kernel:0
encoder1/transformer/layer_6/intermediate/bias:0
encoder1/transformer/layer_6/output/kernel:0
encoder1/transformer/layer_6/output/bias:0
encoder1/transformer/layer_6/output_layer_norm/gamma:0
encoder1/transformer/layer_6/output_layer_norm/beta:0
encoder1/transformer/layer_7/self_attention/key/kernel:0
encoder1/transformer/layer_7/self_attention/key/bias:0
encoder1/transformer/layer_7/self_attention/attention_output/kernel:0
encoder1/transformer/layer_7/self_attention/attention_output/bias:0
encoder1/transformer/layer_7/self_attention/query/kernel:0
encoder1/transformer/layer_7/self_attention/query/bias:0
encoder1/transformer/layer_7/self_attention/value/kernel:0
encoder1/transformer/layer_7/self_attention/value/bias:0
encoder1/transformer/layer_7/self_attention_layer_norm/gamma:0
encoder1/transformer/layer_7/self_attention_layer_norm/beta:0
encoder1/transformer/layer_7/intermediate/kernel:0
encoder1/transformer/layer_7/intermediate/bias:0
encoder1/transformer/layer_7/output/kernel:0
encoder1/transformer/layer_7/output/bias:0
encoder1/transformer/layer_7/output_layer_norm/gamma:0
encoder1/transformer/layer_7/output_layer_norm/beta:0
encoder1/transformer/layer_8/self_attention/key/kernel:0
encoder1/transformer/layer_8/self_attention/key/bias:0
encoder1/transformer/layer_8/self_attention/attention_output/kernel:0
encoder1/transformer/layer_8/self_attention/attention_output/bias:0
encoder1/transformer/layer_8/self_attention/query/kernel:0
encoder1/transformer/layer_8/self_attention/query/bias:0
encoder1/transformer/layer_8/self_attention/value/kernel:0
encoder1/transformer/layer_8/self_attention/value/bias:0
encoder1/transformer/layer_8/self_attention_layer_norm/gamma:0
encoder1/transformer/layer_8/self_attention_layer_norm/beta:0
encoder1/transformer/layer_8/intermediate/kernel:0
encoder1/transformer/layer_8/intermediate/bias:0
encoder1/transformer/layer_8/output/kernel:0
encoder1/transformer/layer_8/output/bias:0
encoder1/transformer/layer_8/output_layer_norm/gamma:0
encoder1/transformer/layer_8/output_layer_norm/beta:0
encoder1/transformer/layer_9/self_attention/key/kernel:0
encoder1/transformer/layer_9/self_attention/key/bias:0
encoder1/transformer/layer_9/self_attention/attention_output/kernel:0
encoder1/transformer/layer_9/self_attention/attention_output/bias:0
encoder1/transformer/layer_9/self_attention/query/kernel:0
encoder1/transformer/layer_9/self_attention/query/bias:0
encoder1/transformer/layer_9/self_attention/value/kernel:0
encoder1/transformer/layer_9/self_attention/value/bias:0
encoder1/transformer/layer_9/self_attention_layer_norm/gamma:0
encoder1/transformer/layer_9/self_attention_layer_norm/beta:0
encoder1/transformer/layer_9/intermediate/kernel:0
encoder1/transformer/layer_9/intermediate/bias:0
encoder1/transformer/layer_9/output/kernel:0
encoder1/transformer/layer_9/output/bias:0
encoder1/transformer/layer_9/output_layer_norm/gamma:0
encoder1/transformer/layer_9/output_layer_norm/beta:0
encoder1/transformer/layer_10/self_attention/key/kernel:0
encoder1/transformer/layer_10/self_attention/key/bias:0
encoder1/transformer/layer_10/self_attention/attention_output/kernel:0
encoder1/transformer/layer_10/self_attention/attention_output/bias:0
encoder1/transformer/layer_10/self_attention/query/kernel:0
encoder1/transformer/layer_10/self_attention/query/bias:0
encoder1/transformer/layer_10/self_attention/value/kernel:0
encoder1/transformer/layer_10/self_attention/value/bias:0
encoder1/transformer/layer_10/self_attention_layer_norm/gamma:0
encoder1/transformer/layer_10/self_attention_layer_norm/beta:0
encoder1/transformer/layer_10/intermediate/kernel:0
encoder1/transformer/layer_10/intermediate/bias:0
encoder1/transformer/layer_10/output/kernel:0
encoder1/transformer/layer_10/output/bias:0
encoder1/transformer/layer_10/output_layer_norm/gamma:0
encoder1/transformer/layer_10/output_layer_norm/beta:0
encoder1/transformer/layer_11/self_attention/key/kernel:0
encoder1/transformer/layer_11/self_attention/key/bias:0
encoder1/transformer/layer_11/self_attention/attention_output/kernel:0
encoder1/transformer/layer_11/self_attention/attention_output/bias:0
encoder1/transformer/layer_11/self_attention/query/kernel:0
encoder1/transformer/layer_11/self_attention/query/bias:0
encoder1/transformer/layer_11/self_attention/value/kernel:0
encoder1/transformer/layer_11/self_attention/value/bias:0
encoder1/transformer/layer_11/self_attention_layer_norm/gamma:0
encoder1/transformer/layer_11/self_attention_layer_norm/beta:0
encoder1/transformer/layer_11/intermediate/kernel:0
encoder1/transformer/layer_11/intermediate/bias:0
encoder1/transformer/layer_11/output/kernel:0
encoder1/transformer/layer_11/output/bias:0
encoder1/transformer/layer_11/output_layer_norm/gamma:0
encoder1/transformer/layer_11/output_layer_norm/beta:0
encoder1/type_embeddings/embeddings:0
"""
name_in_ts_model = """bert_encoder_module/encoder1/word_embeddings/embeddings:0
bert_encoder_module/encoder1/position_embedding/embeddings:0
bert_encoder_module/encoder1/type_embeddings/embeddings:0
bert_encoder_module/encoder1/embeddings/layer_norm/gamma:0
bert_encoder_module/encoder1/embeddings/layer_norm/beta:0
bert_encoder_module/encoder1/transformer/layer_0/self_attention/query/kernel:0
bert_encoder_module/encoder1/transformer/layer_0/self_attention/query/bias:0
bert_encoder_module/encoder1/transformer/layer_0/self_attention/key/kernel:0
bert_encoder_module/encoder1/transformer/layer_0/self_attention/key/bias:0
bert_encoder_module/encoder1/transformer/layer_0/self_attention/value/kernel:0
bert_encoder_module/encoder1/transformer/layer_0/self_attention/value/bias:0
bert_encoder_module/encoder1/transformer/layer_0/self_attention/attention_output/kernel:0
bert_encoder_module/encoder1/transformer/layer_0/self_attention/attention_output/bias:0
bert_encoder_module/encoder1/transformer/layer_0/self_attention_layer_norm/gamma:0
bert_encoder_module/encoder1/transformer/layer_0/self_attention_layer_norm/beta:0
bert_encoder_module/encoder1/transformer/layer_0/intermediate/kernel:0
bert_encoder_module/encoder1/transformer/layer_0/intermediate/bias:0
bert_encoder_module/encoder1/transformer/layer_0/output/kernel:0
bert_encoder_module/encoder1/transformer/layer_0/output/bias:0
bert_encoder_module/encoder1/transformer/layer_0/output_layer_norm/gamma:0
bert_encoder_module/encoder1/transformer/layer_0/output_layer_norm/beta:0
bert_encoder_module/encoder1/transformer/layer_1/self_attention/query/kernel:0
bert_encoder_module/encoder1/transformer/layer_1/self_attention/query/bias:0
bert_encoder_module/encoder1/transformer/layer_1/self_attention/key/kernel:0
bert_encoder_module/encoder1/transformer/layer_1/self_attention/key/bias:0
bert_encoder_module/encoder1/transformer/layer_1/self_attention/value/kernel:0
bert_encoder_module/encoder1/transformer/layer_1/self_attention/value/bias:0
bert_encoder_module/encoder1/transformer/layer_1/self_attention/attention_output/kernel:0
bert_encoder_module/encoder1/transformer/layer_1/self_attention/attention_output/bias:0
bert_encoder_module/encoder1/transformer/layer_1/self_attention_layer_norm/gamma:0
bert_encoder_module/encoder1/transformer/layer_1/self_attention_layer_norm/beta:0
bert_encoder_module/encoder1/transformer/layer_1/intermediate/kernel:0
bert_encoder_module/encoder1/transformer/layer_1/intermediate/bias:0
bert_encoder_module/encoder1/transformer/layer_1/output/kernel:0
bert_encoder_module/encoder1/transformer/layer_1/output/bias:0
bert_encoder_module/encoder1/transformer/layer_1/output_layer_norm/gamma:0
bert_encoder_module/encoder1/transformer/layer_1/output_layer_norm/beta:0
bert_encoder_module/encoder1/transformer/layer_2/self_attention/query/kernel:0
bert_encoder_module/encoder1/transformer/layer_2/self_attention/query/bias:0
bert_encoder_module/encoder1/transformer/layer_2/self_attention/key/kernel:0
bert_encoder_module/encoder1/transformer/layer_2/self_attention/key/bias:0
bert_encoder_module/encoder1/transformer/layer_2/self_attention/value/kernel:0
bert_encoder_module/encoder1/transformer/layer_2/self_attention/value/bias:0
bert_encoder_module/encoder1/transformer/layer_2/self_attention/attention_output/kernel:0
bert_encoder_module/encoder1/transformer/layer_2/self_attention/attention_output/bias:0
bert_encoder_module/encoder1/transformer/layer_2/self_attention_layer_norm/gamma:0
bert_encoder_module/encoder1/transformer/layer_2/self_attention_layer_norm/beta:0
bert_encoder_module/encoder1/transformer/layer_2/intermediate/kernel:0
bert_encoder_module/encoder1/transformer/layer_2/intermediate/bias:0
bert_encoder_module/encoder1/transformer/layer_2/output/kernel:0
bert_encoder_module/encoder1/transformer/layer_2/output/bias:0
bert_encoder_module/encoder1/transformer/layer_2/output_layer_norm/gamma:0
bert_encoder_module/encoder1/transformer/layer_2/output_layer_norm/beta:0
bert_encoder_module/encoder1/transformer/layer_3/self_attention/query/kernel:0
bert_encoder_module/encoder1/transformer/layer_3/self_attention/query/bias:0
bert_encoder_module/encoder1/transformer/layer_3/self_attention/key/kernel:0
bert_encoder_module/encoder1/transformer/layer_3/self_attention/key/bias:0
bert_encoder_module/encoder1/transformer/layer_3/self_attention/value/kernel:0
bert_encoder_module/encoder1/transformer/layer_3/self_attention/value/bias:0
bert_encoder_module/encoder1/transformer/layer_3/self_attention/attention_output/kernel:0
bert_encoder_module/encoder1/transformer/layer_3/self_attention/attention_output/bias:0
bert_encoder_module/encoder1/transformer/layer_3/self_attention_layer_norm/gamma:0
bert_encoder_module/encoder1/transformer/layer_3/self_attention_layer_norm/beta:0
bert_encoder_module/encoder1/transformer/layer_3/intermediate/kernel:0
bert_encoder_module/encoder1/transformer/layer_3/intermediate/bias:0
bert_encoder_module/encoder1/transformer/layer_3/output/kernel:0
bert_encoder_module/encoder1/transformer/layer_3/output/bias:0
bert_encoder_module/encoder1/transformer/layer_3/output_layer_norm/gamma:0
bert_encoder_module/encoder1/transformer/layer_3/output_layer_norm/beta:0
bert_encoder_module/encoder1/transformer/layer_4/self_attention/query/kernel:0
bert_encoder_module/encoder1/transformer/layer_4/self_attention/query/bias:0
bert_encoder_module/encoder1/transformer/layer_4/self_attention/key/kernel:0
bert_encoder_module/encoder1/transformer/layer_4/self_attention/key/bias:0
bert_encoder_module/encoder1/transformer/layer_4/self_attention/value/kernel:0
bert_encoder_module/encoder1/transformer/layer_4/self_attention/value/bias:0
bert_encoder_module/encoder1/transformer/layer_4/self_attention/attention_output/kernel:0
bert_encoder_module/encoder1/transformer/layer_4/self_attention/attention_output/bias:0
bert_encoder_module/encoder1/transformer/layer_4/self_attention_layer_norm/gamma:0
bert_encoder_module/encoder1/transformer/layer_4/self_attention_layer_norm/beta:0
bert_encoder_module/encoder1/transformer/layer_4/intermediate/kernel:0
bert_encoder_module/encoder1/transformer/layer_4/intermediate/bias:0
bert_encoder_module/encoder1/transformer/layer_4/output/kernel:0
bert_encoder_module/encoder1/transformer/layer_4/output/bias:0
bert_encoder_module/encoder1/transformer/layer_4/output_layer_norm/gamma:0
bert_encoder_module/encoder1/transformer/layer_4/output_layer_norm/beta:0
bert_encoder_module/encoder1/transformer/layer_5/self_attention/query/kernel:0
bert_encoder_module/encoder1/transformer/layer_5/self_attention/query/bias:0
bert_encoder_module/encoder1/transformer/layer_5/self_attention/key/kernel:0
bert_encoder_module/encoder1/transformer/layer_5/self_attention/key/bias:0
bert_encoder_module/encoder1/transformer/layer_5/self_attention/value/kernel:0
bert_encoder_module/encoder1/transformer/layer_5/self_attention/value/bias:0
bert_encoder_module/encoder1/transformer/layer_5/self_attention/attention_output/kernel:0
bert_encoder_module/encoder1/transformer/layer_5/self_attention/attention_output/bias:0
bert_encoder_module/encoder1/transformer/layer_5/self_attention_layer_norm/gamma:0
bert_encoder_module/encoder1/transformer/layer_5/self_attention_layer_norm/beta:0
bert_encoder_module/encoder1/transformer/layer_5/intermediate/kernel:0
bert_encoder_module/encoder1/transformer/layer_5/intermediate/bias:0
bert_encoder_module/encoder1/transformer/layer_5/output/kernel:0
bert_encoder_module/encoder1/transformer/layer_5/output/bias:0
bert_encoder_module/encoder1/transformer/layer_5/output_layer_norm/gamma:0
bert_encoder_module/encoder1/transformer/layer_5/output_layer_norm/beta:0
bert_encoder_module/encoder1/transformer/layer_6/self_attention/query/kernel:0
bert_encoder_module/encoder1/transformer/layer_6/self_attention/query/bias:0
bert_encoder_module/encoder1/transformer/layer_6/self_attention/key/kernel:0
bert_encoder_module/encoder1/transformer/layer_6/self_attention/key/bias:0
bert_encoder_module/encoder1/transformer/layer_6/self_attention/value/kernel:0
bert_encoder_module/encoder1/transformer/layer_6/self_attention/value/bias:0
bert_encoder_module/encoder1/transformer/layer_6/self_attention/attention_output/kernel:0
bert_encoder_module/encoder1/transformer/layer_6/self_attention/attention_output/bias:0
bert_encoder_module/encoder1/transformer/layer_6/self_attention_layer_norm/gamma:0
bert_encoder_module/encoder1/transformer/layer_6/self_attention_layer_norm/beta:0
bert_encoder_module/encoder1/transformer/layer_6/intermediate/kernel:0
bert_encoder_module/encoder1/transformer/layer_6/intermediate/bias:0
bert_encoder_module/encoder1/transformer/layer_6/output/kernel:0
bert_encoder_module/encoder1/transformer/layer_6/output/bias:0
bert_encoder_module/encoder1/transformer/layer_6/output_layer_norm/gamma:0
bert_encoder_module/encoder1/transformer/layer_6/output_layer_norm/beta:0
bert_encoder_module/encoder1/transformer/layer_7/self_attention/query/kernel:0
bert_encoder_module/encoder1/transformer/layer_7/self_attention/query/bias:0
bert_encoder_module/encoder1/transformer/layer_7/self_attention/key/kernel:0
bert_encoder_module/encoder1/transformer/layer_7/self_attention/key/bias:0
bert_encoder_module/encoder1/transformer/layer_7/self_attention/value/kernel:0
bert_encoder_module/encoder1/transformer/layer_7/self_attention/value/bias:0
bert_encoder_module/encoder1/transformer/layer_7/self_attention/attention_output/kernel:0
bert_encoder_module/encoder1/transformer/layer_7/self_attention/attention_output/bias:0
bert_encoder_module/encoder1/transformer/layer_7/self_attention_layer_norm/gamma:0
bert_encoder_module/encoder1/transformer/layer_7/self_attention_layer_norm/beta:0
bert_encoder_module/encoder1/transformer/layer_7/intermediate/kernel:0
bert_encoder_module/encoder1/transformer/layer_7/intermediate/bias:0
bert_encoder_module/encoder1/transformer/layer_7/output/kernel:0
bert_encoder_module/encoder1/transformer/layer_7/output/bias:0
bert_encoder_module/encoder1/transformer/layer_7/output_layer_norm/gamma:0
bert_encoder_module/encoder1/transformer/layer_7/output_layer_norm/beta:0
bert_encoder_module/encoder1/transformer/layer_8/self_attention/query/kernel:0
bert_encoder_module/encoder1/transformer/layer_8/self_attention/query/bias:0
bert_encoder_module/encoder1/transformer/layer_8/self_attention/key/kernel:0
bert_encoder_module/encoder1/transformer/layer_8/self_attention/key/bias:0
bert_encoder_module/encoder1/transformer/layer_8/self_attention/value/kernel:0
bert_encoder_module/encoder1/transformer/layer_8/self_attention/value/bias:0
bert_encoder_module/encoder1/transformer/layer_8/self_attention/attention_output/kernel:0
bert_encoder_module/encoder1/transformer/layer_8/self_attention/attention_output/bias:0
bert_encoder_module/encoder1/transformer/layer_8/self_attention_layer_norm/gamma:0
bert_encoder_module/encoder1/transformer/layer_8/self_attention_layer_norm/beta:0
bert_encoder_module/encoder1/transformer/layer_8/intermediate/kernel:0
bert_encoder_module/encoder1/transformer/layer_8/intermediate/bias:0
bert_encoder_module/encoder1/transformer/layer_8/output/kernel:0
bert_encoder_module/encoder1/transformer/layer_8/output/bias:0
bert_encoder_module/encoder1/transformer/layer_8/output_layer_norm/gamma:0
bert_encoder_module/encoder1/transformer/layer_8/output_layer_norm/beta:0
bert_encoder_module/encoder1/transformer/layer_9/self_attention/query/kernel:0
bert_encoder_module/encoder1/transformer/layer_9/self_attention/query/bias:0
bert_encoder_module/encoder1/transformer/layer_9/self_attention/key/kernel:0
bert_encoder_module/encoder1/transformer/layer_9/self_attention/key/bias:0
bert_encoder_module/encoder1/transformer/layer_9/self_attention/value/kernel:0
bert_encoder_module/encoder1/transformer/layer_9/self_attention/value/bias:0
bert_encoder_module/encoder1/transformer/layer_9/self_attention/attention_output/kernel:0
bert_encoder_module/encoder1/transformer/layer_9/self_attention/attention_output/bias:0
bert_encoder_module/encoder1/transformer/layer_9/self_attention_layer_norm/gamma:0
bert_encoder_module/encoder1/transformer/layer_9/self_attention_layer_norm/beta:0
bert_encoder_module/encoder1/transformer/layer_9/intermediate/kernel:0
bert_encoder_module/encoder1/transformer/layer_9/intermediate/bias:0
bert_encoder_module/encoder1/transformer/layer_9/output/kernel:0
bert_encoder_module/encoder1/transformer/layer_9/output/bias:0
bert_encoder_module/encoder1/transformer/layer_9/output_layer_norm/gamma:0
bert_encoder_module/encoder1/transformer/layer_9/output_layer_norm/beta:0
bert_encoder_module/encoder1/transformer/layer_10/self_attention/query/kernel:0
bert_encoder_module/encoder1/transformer/layer_10/self_attention/query/bias:0
bert_encoder_module/encoder1/transformer/layer_10/self_attention/key/kernel:0
bert_encoder_module/encoder1/transformer/layer_10/self_attention/key/bias:0
bert_encoder_module/encoder1/transformer/layer_10/self_attention/value/kernel:0
bert_encoder_module/encoder1/transformer/layer_10/self_attention/value/bias:0
bert_encoder_module/encoder1/transformer/layer_10/self_attention/attention_output/kernel:0
bert_encoder_module/encoder1/transformer/layer_10/self_attention/attention_output/bias:0
bert_encoder_module/encoder1/transformer/layer_10/self_attention_layer_norm/gamma:0
bert_encoder_module/encoder1/transformer/layer_10/self_attention_layer_norm/beta:0
bert_encoder_module/encoder1/transformer/layer_10/intermediate/kernel:0
bert_encoder_module/encoder1/transformer/layer_10/intermediate/bias:0
bert_encoder_module/encoder1/transformer/layer_10/output/kernel:0
bert_encoder_module/encoder1/transformer/layer_10/output/bias:0
bert_encoder_module/encoder1/transformer/layer_10/output_layer_norm/gamma:0
bert_encoder_module/encoder1/transformer/layer_10/output_layer_norm/beta:0
bert_encoder_module/encoder1/transformer/layer_11/self_attention/query/kernel:0
bert_encoder_module/encoder1/transformer/layer_11/self_attention/query/bias:0
bert_encoder_module/encoder1/transformer/layer_11/self_attention/key/kernel:0
bert_encoder_module/encoder1/transformer/layer_11/self_attention/key/bias:0
bert_encoder_module/encoder1/transformer/layer_11/self_attention/value/kernel:0
bert_encoder_module/encoder1/transformer/layer_11/self_attention/value/bias:0
bert_encoder_module/encoder1/transformer/layer_11/self_attention/attention_output/kernel:0
bert_encoder_module/encoder1/transformer/layer_11/self_attention/attention_output/bias:0
bert_encoder_module/encoder1/transformer/layer_11/self_attention_layer_norm/gamma:0
bert_encoder_module/encoder1/transformer/layer_11/self_attention_layer_norm/beta:0
bert_encoder_module/encoder1/transformer/layer_11/intermediate/kernel:0
bert_encoder_module/encoder1/transformer/layer_11/intermediate/bias:0
bert_encoder_module/encoder1/transformer/layer_11/output/kernel:0
bert_encoder_module/encoder1/transformer/layer_11/output/bias:0
bert_encoder_module/encoder1/transformer/layer_11/output_layer_norm/gamma:0
bert_encoder_module/encoder1/transformer/layer_11/output_layer_norm/beta:0
bert_encoder_module/encoder1/pooler_transform/kernel:0
bert_encoder_module/encoder1/pooler_transform/bias:0"""

v1_ckpt_variables_raw = """bert/embeddings/LayerNorm/beta
bert/embeddings/LayerNorm/gamma
bert/embeddings/position_embeddings
bert/embeddings/token_type_embeddings
bert/embeddings/word_embeddings
bert/encoder/layer_0/attention/output/LayerNorm/beta
bert/encoder/layer_0/attention/output/LayerNorm/gamma
bert/encoder/layer_0/attention/output/dense/bias
bert/encoder/layer_0/attention/output/dense/kernel
bert/encoder/layer_0/attention/self/key/bias
bert/encoder/layer_0/attention/self/key/kernel
bert/encoder/layer_0/attention/self/query/bias
bert/encoder/layer_0/attention/self/query/kernel
bert/encoder/layer_0/attention/self/value/bias
bert/encoder/layer_0/attention/self/value/kernel
bert/encoder/layer_0/intermediate/dense/bias
bert/encoder/layer_0/intermediate/dense/kernel
bert/encoder/layer_0/output/LayerNorm/beta
bert/encoder/layer_0/output/LayerNorm/gamma
bert/encoder/layer_0/output/dense/bias
bert/encoder/layer_0/output/dense/kernel
bert/encoder/layer_1/attention/output/LayerNorm/beta
bert/encoder/layer_1/attention/output/LayerNorm/gamma
bert/encoder/layer_1/attention/output/dense/bias
bert/encoder/layer_1/attention/output/dense/kernel
bert/encoder/layer_1/attention/self/key/bias
bert/encoder/layer_1/attention/self/key/kernel
bert/encoder/layer_1/attention/self/query/bias
bert/encoder/layer_1/attention/self/query/kernel
bert/encoder/layer_1/attention/self/value/bias
bert/encoder/layer_1/attention/self/value/kernel
bert/encoder/layer_1/intermediate/dense/bias
bert/encoder/layer_1/intermediate/dense/kernel
bert/encoder/layer_1/output/LayerNorm/beta
bert/encoder/layer_1/output/LayerNorm/gamma
bert/encoder/layer_1/output/dense/bias
bert/encoder/layer_1/output/dense/kernel
bert/encoder/layer_10/attention/output/LayerNorm/beta
bert/encoder/layer_10/attention/output/LayerNorm/gamma
bert/encoder/layer_10/attention/output/dense/bias
bert/encoder/layer_10/attention/output/dense/kernel
bert/encoder/layer_10/attention/self/key/bias
bert/encoder/layer_10/attention/self/key/kernel
bert/encoder/layer_10/attention/self/query/bias
bert/encoder/layer_10/attention/self/query/kernel
bert/encoder/layer_10/attention/self/value/bias
bert/encoder/layer_10/attention/self/value/kernel
bert/encoder/layer_10/intermediate/dense/bias
bert/encoder/layer_10/intermediate/dense/kernel
bert/encoder/layer_10/output/LayerNorm/beta
bert/encoder/layer_10/output/LayerNorm/gamma
bert/encoder/layer_10/output/dense/bias
bert/encoder/layer_10/output/dense/kernel
bert/encoder/layer_11/attention/output/LayerNorm/beta
bert/encoder/layer_11/attention/output/LayerNorm/gamma
bert/encoder/layer_11/attention/output/dense/bias
bert/encoder/layer_11/attention/output/dense/kernel
bert/encoder/layer_11/attention/self/key/bias
bert/encoder/layer_11/attention/self/key/kernel
bert/encoder/layer_11/attention/self/query/bias
bert/encoder/layer_11/attention/self/query/kernel
bert/encoder/layer_11/attention/self/value/bias
bert/encoder/layer_11/attention/self/value/kernel
bert/encoder/layer_11/intermediate/dense/bias
bert/encoder/layer_11/intermediate/dense/kernel
bert/encoder/layer_11/output/LayerNorm/beta
bert/encoder/layer_11/output/LayerNorm/gamma
bert/encoder/layer_11/output/dense/bias
bert/encoder/layer_11/output/dense/kernel
bert/encoder/layer_2/attention/output/LayerNorm/beta
bert/encoder/layer_2/attention/output/LayerNorm/gamma
bert/encoder/layer_2/attention/output/dense/bias
bert/encoder/layer_2/attention/output/dense/kernel
bert/encoder/layer_2/attention/self/key/bias
bert/encoder/layer_2/attention/self/key/kernel
bert/encoder/layer_2/attention/self/query/bias
bert/encoder/layer_2/attention/self/query/kernel
bert/encoder/layer_2/attention/self/value/bias
bert/encoder/layer_2/attention/self/value/kernel
bert/encoder/layer_2/intermediate/dense/bias
bert/encoder/layer_2/intermediate/dense/kernel
bert/encoder/layer_2/output/LayerNorm/beta
bert/encoder/layer_2/output/LayerNorm/gamma
bert/encoder/layer_2/output/dense/bias
bert/encoder/layer_2/output/dense/kernel
bert/encoder/layer_3/attention/output/LayerNorm/beta
bert/encoder/layer_3/attention/output/LayerNorm/gamma
bert/encoder/layer_3/attention/output/dense/bias
bert/encoder/layer_3/attention/output/dense/kernel
bert/encoder/layer_3/attention/self/key/bias
bert/encoder/layer_3/attention/self/key/kernel
bert/encoder/layer_3/attention/self/query/bias
bert/encoder/layer_3/attention/self/query/kernel
bert/encoder/layer_3/attention/self/value/bias
bert/encoder/layer_3/attention/self/value/kernel
bert/encoder/layer_3/intermediate/dense/bias
bert/encoder/layer_3/intermediate/dense/kernel
bert/encoder/layer_3/output/LayerNorm/beta
bert/encoder/layer_3/output/LayerNorm/gamma
bert/encoder/layer_3/output/dense/bias
bert/encoder/layer_3/output/dense/kernel
bert/encoder/layer_4/attention/output/LayerNorm/beta
bert/encoder/layer_4/attention/output/LayerNorm/gamma
bert/encoder/layer_4/attention/output/dense/bias
bert/encoder/layer_4/attention/output/dense/kernel
bert/encoder/layer_4/attention/self/key/bias
bert/encoder/layer_4/attention/self/key/kernel
bert/encoder/layer_4/attention/self/query/bias
bert/encoder/layer_4/attention/self/query/kernel
bert/encoder/layer_4/attention/self/value/bias
bert/encoder/layer_4/attention/self/value/kernel
bert/encoder/layer_4/intermediate/dense/bias
bert/encoder/layer_4/intermediate/dense/kernel
bert/encoder/layer_4/output/LayerNorm/beta
bert/encoder/layer_4/output/LayerNorm/gamma
bert/encoder/layer_4/output/dense/bias
bert/encoder/layer_4/output/dense/kernel
bert/encoder/layer_5/attention/output/LayerNorm/beta
bert/encoder/layer_5/attention/output/LayerNorm/gamma
bert/encoder/layer_5/attention/output/dense/bias
bert/encoder/layer_5/attention/output/dense/kernel
bert/encoder/layer_5/attention/self/key/bias
bert/encoder/layer_5/attention/self/key/kernel
bert/encoder/layer_5/attention/self/query/bias
bert/encoder/layer_5/attention/self/query/kernel
bert/encoder/layer_5/attention/self/value/bias
bert/encoder/layer_5/attention/self/value/kernel
bert/encoder/layer_5/intermediate/dense/bias
bert/encoder/layer_5/intermediate/dense/kernel
bert/encoder/layer_5/output/LayerNorm/beta
bert/encoder/layer_5/output/LayerNorm/gamma
bert/encoder/layer_5/output/dense/bias
bert/encoder/layer_5/output/dense/kernel
bert/encoder/layer_6/attention/output/LayerNorm/beta
bert/encoder/layer_6/attention/output/LayerNorm/gamma
bert/encoder/layer_6/attention/output/dense/bias
bert/encoder/layer_6/attention/output/dense/kernel
bert/encoder/layer_6/attention/self/key/bias
bert/encoder/layer_6/attention/self/key/kernel
bert/encoder/layer_6/attention/self/query/bias
bert/encoder/layer_6/attention/self/query/kernel
bert/encoder/layer_6/attention/self/value/bias
bert/encoder/layer_6/attention/self/value/kernel
bert/encoder/layer_6/intermediate/dense/bias
bert/encoder/layer_6/intermediate/dense/kernel
bert/encoder/layer_6/output/LayerNorm/beta
bert/encoder/layer_6/output/LayerNorm/gamma
bert/encoder/layer_6/output/dense/bias
bert/encoder/layer_6/output/dense/kernel
bert/encoder/layer_7/attention/output/LayerNorm/beta
bert/encoder/layer_7/attention/output/LayerNorm/gamma
bert/encoder/layer_7/attention/output/dense/bias
bert/encoder/layer_7/attention/output/dense/kernel
bert/encoder/layer_7/attention/self/key/bias
bert/encoder/layer_7/attention/self/key/kernel
bert/encoder/layer_7/attention/self/query/bias
bert/encoder/layer_7/attention/self/query/kernel
bert/encoder/layer_7/attention/self/value/bias
bert/encoder/layer_7/attention/self/value/kernel
bert/encoder/layer_7/intermediate/dense/bias
bert/encoder/layer_7/intermediate/dense/kernel
bert/encoder/layer_7/output/LayerNorm/beta
bert/encoder/layer_7/output/LayerNorm/gamma
bert/encoder/layer_7/output/dense/bias
bert/encoder/layer_7/output/dense/kernel
bert/encoder/layer_8/attention/output/LayerNorm/beta
bert/encoder/layer_8/attention/output/LayerNorm/gamma
bert/encoder/layer_8/attention/output/dense/bias
bert/encoder/layer_8/attention/output/dense/kernel
bert/encoder/layer_8/attention/self/key/bias
bert/encoder/layer_8/attention/self/key/kernel
bert/encoder/layer_8/attention/self/query/bias
bert/encoder/layer_8/attention/self/query/kernel
bert/encoder/layer_8/attention/self/value/bias
bert/encoder/layer_8/attention/self/value/kernel
bert/encoder/layer_8/intermediate/dense/bias
bert/encoder/layer_8/intermediate/dense/kernel
bert/encoder/layer_8/output/LayerNorm/beta
bert/encoder/layer_8/output/LayerNorm/gamma
bert/encoder/layer_8/output/dense/bias
bert/encoder/layer_8/output/dense/kernel
bert/encoder/layer_9/attention/output/LayerNorm/beta
bert/encoder/layer_9/attention/output/LayerNorm/gamma
bert/encoder/layer_9/attention/output/dense/bias
bert/encoder/layer_9/attention/output/dense/kernel
bert/encoder/layer_9/attention/self/key/bias
bert/encoder/layer_9/attention/self/key/kernel
bert/encoder/layer_9/attention/self/query/bias
bert/encoder/layer_9/attention/self/query/kernel
bert/encoder/layer_9/attention/self/value/bias
bert/encoder/layer_9/attention/self/value/kernel
bert/encoder/layer_9/intermediate/dense/bias
bert/encoder/layer_9/intermediate/dense/kernel
bert/encoder/layer_9/output/LayerNorm/beta
bert/encoder/layer_9/output/LayerNorm/gamma
bert/encoder/layer_9/output/dense/bias
bert/encoder/layer_9/output/dense/kernel
bert/pooler/dense/bias
bert/pooler/dense/kernel
cls/predictions/output_bias
cls/predictions/transform/LayerNorm/beta
cls/predictions/transform/LayerNorm/gamma
cls/predictions/transform/dense/bias
cls/predictions/transform/dense/kernel
cls/seq_relationship/output_bias
cls/seq_relationship/output_weights"""